### ISSUE TITLE
Need to migrate the code from callbacks to promises.

### ISSUE THREAD

**Issue by fasidOnGit** [Firnaa5/malaria#1]
Currently, I see the code uses a library called `request` to interact with the EMBL RESTful API. Since the use of callbacks is pretty old and let's move all the uses of callbacks into promises. 
there are tons of promises based libraries for handling RESTful APIs. Eg: [Axios](https://www.npmjs.com/package/axios)

**Comment by Firnaa5** [comment]
I have pushed the code in branch named issue1

**Comment by fasidOnGit** [comment]
in the description of your Pull request please write FIxes #1

**Comment by fasidOnGit** [comment]
ok create a Pull request
